// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Query = 1,
  SelectQuery = 2,
  Select = 3,
  FieldList = 4,
  Asterisk = 5,
  GitInfo = 6,
  Problems = 7,
  Arch = 8,
  Comma = 9,
  From = 10,
  Project = 11
