// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Query = 1,
  SelectQuery = 2,
  Select = 3,
  FieldList = 4,
  Asterisk = 5,
  Field = 6,
  GitInfo = 7,
  Problems = 8,
  Arch = 9,
  Comma = 10,
  From = 11,
  Project = 12
